---
- hosts: control_plane
  become: yes
  become_user: ubuntu
  tasks:
    - name: Use kubectl to destroy services
      shell: "kubectl delete -f {{ item }}"
      args:
        chdir: $HOME
      with_items:
        - atlantis.yml
        - flask-honeycomb.yml
        - flask-newrelic.yml
        - leza.yml
        - www-apache.yml
        - www-nginx.yml
        - hello-kubernetes.yml
        - echo.yml
        - fo.yml
        - pod.yml
        - elk.yml
        - beats.yml
        - hello-kubernetes.yml
      ignore_errors: true

    - name: Use kubectl to delete pvc
      shell: "kubectl delete pvc {{ item }}"
      args:
        chdir: $HOME
      with_items:
        - csi-pvc
        - elastic-*
        - logstash-*
      ignore_errors: true

    - name: delete all old files
      file:
        path: "$HOME/{{ item }}"
        state: absent
      with_items:
        - atlantis.yml
        - flask-honeycomb.yml
        - flask-newrelic.yml
        - leza.yml
        - www-apache.yml
        - www-nginx.yml
        - hello-kubernetes.yml
        - echo.yml
        - fo.yml
        - atlantis.txt
        - flask-honeycomb.txt
        - flask-newrelic.txt
        - leza.txt
        - www-apache.txt
        - www-nginx.txt
        - hello-kubernetes.txt
        - echo.txt
        - fo.txt
        - pod.txt
        - pvc.txt
        - beats.txt

    - name: Use helm to destroy kubeview
      shell: "helm uninstall {{ item }}"
      args:
        chdir: $HOME
      with_items:
        - kubeview
      ignore_errors: true

    - name: Pause for 30 seconds before taking down DNS
      ansible.builtin.pause:
        seconds: 30

    - name: Use helm to destroy DNS & Ingress
      shell: "helm uninstall {{ item }}"
      args:
        chdir: $HOME
      with_items:
        - external-dns
        - ingress-nginx
      ignore_errors: true
