---
- hosts: control_plane
  become: yes
  become_user: ubuntu
  vars:
    helm_version: '3.10.2'
  tasks:
    - name: Template the helm dns values file over
      template:
        src: externaldns-values.yaml.j2
        dest: $HOME/externaldns-values.yaml
      tags:
        - build

    - name: Install external dns via helm
      shell: helm install external-dns bitnami/external-dns -f externaldns-values.yaml >> external-dns.txt
      args:
        chdir: $HOME
        creates: external-dns.txt
      tags:
        - build

    - name: Use helm to delete external-dns
      shell: helm uninstall external-dns 
      args:
        chdir: $HOME
        removes: external-dns.txt
      tags:
        - destroy

    - name: Delete the lock file
      file:
        path: $HOME/external-dns.txt
        state: absent
      tags:
        - destroy
