---
- hosts: control_plane
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Copy the hello kubernetes template
      copy:
        src: hello-kubernetes.yml
        dest: $HOME/

    - name: Use kubectl to deploy the hello-kubernetes service
      shell: kubectl apply -f hello-kubernetes.yml >> hello-kubernetes.txt
      args:
        chdir: $HOME
        creates: hello-kubernetes.txt

    - name: Copy the hello kubernetes ingress template
      copy:
        src: hello-kubernetes-ingress.yml
        dest: $HOME/

    - name: Use kubectl to deploy the hello-kubernetes-ingress service
      shell: kubectl apply -f hello-kubernetes-ingress.yml >> hello-kubernetes-ingress.txt
      args:
        chdir: $HOME
        creates: hello-kubernetes-ingress.txt
