---
- hosts: control_plane
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Download Kubeview
      unarchive: 
        src: https://github.com/benc-uk/kubeview/releases/download/0.1.31/kubeview-0.1.31.tgz
        dest: $HOME
        remote_src: true
      tags:
        - build

    - name: Copy our values file over
      copy:
        src: kubeview-values.yaml
        dest: $HOME/kubeview/values.yml
      tags:
        - build

    - name: Install Kubeview
      shell: helm install kubeview ./kubeview/ -f kubeview/values.yaml
      args:
        chdir: $HOME
      tags:
        - build

    - name: Delete kubevirw
      shell: helm uninstall kubeview
      args:
        chdir: $HOME
      tags:
        - destroy
