---
- name: Import and execute the Prequesitues playbook
  ansible.builtin.import_playbook: prereqs.yml

#- name: Import and execute the playbook for new relic
#ansible.builtin.import_playbook: new_relic.yml

- name: Import and execute container runtime interface playbook
  ansible.builtin.import_playbook: cri.yml

- name: Import and execute kubernetes playbook
  ansible.builtin.import_playbook: kubernetes.yml

- name: Install helm as a package manager for k8s
  ansible.builtin.import_playbook: helm.yml

- name: Import and execute the cert-manager
  ansible.builtin.import_playbook: cert-manager.yml

- name: Import and execute the secrets playbook
  ansible.builtin.import_playbook: secrets.yml

- name: Import and execute the ingress controller playbook
  ansible.builtin.import_playbook: ingress.yml

# @bug: externaldns fails when source: ingress is used at the same time as source: istio-gateway
#- name: Import and execute the istio playbook
  #ansible.builtin.import_playbook: istio.yml

- name: Use helm to install externaldns
  ansible.builtin.import_playbook: externaldns.yml

- name: Import and execute the doccm playbook
  ansible.builtin.import_playbook: do_ccm.yml

- name: Import and execute the docsi playbook
  ansible.builtin.import_playbook: do_csi.yml

- name: Import and execute the kubeview playbook
  ansible.builtin.import_playbook: kubeview.yml

- name: Import and execute the vpn playbook
  ansible.builtin.import_playbook: vpn.yml

- name: Import and execute the keycloak playbook
  ansible.builtin.import_playbook: keycloak.yml

#- name: Launch the elastic stack in the cluster
  #ansible.builtin.import_playbook: elastic.yml

- name: Import and execute the playbook for financial occult
  ansible.builtin.import_playbook: fo.yml

#- name: Instrument the OS with elastic agents
  #ansible.builtin.import_playbook: instrument.yml

#- name: Import and execute the bookinfo_apps playbook
  #ansible.builtin.import_playbook: bookinfo_apps.yml
