---
- hosts: control_plane
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
   - name: Template the secret file to the system
     template: 
      src: secret.yml.j2
      dest: $HOME/secret.yml

   - name: Use Kubectl to apply the secret
     shell: kubectl apply -f secret.yml
     args:
       chdir: $HOME

# Need to delete the secret file from the filesystem
