---
- hosts: worker-1.do.iot4.net
  become: yes
  gather_facts: false
  tasks:
    - name: Add nginx web server on worker-1 using apt
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Transfer over our index.html file
      copy:
        src: index.html
        dest: /var/www/html
