- name: Build the stack
  become: true
  hosts: east
  roles:
  tasks:

  - name: Install yum dependencies
    yum:
      name: [httpd, python-pip, python-wheel]
      update_cache: yes
      state: present

  # Check to make sure nvme disks are partitioned and mounted.
  - name: "Stat the /data dir to see if it exists"
    stat:
        path: "/data"
    register: data

  - name: "Stat the {{ html_root }} to see if its dir or link"
    stat:
        path: "{{ html_root }}"
    register: sym

  - name: "Sync {{ s3_target }} to /data"
    shell: "aws s3 sync {{ s3_target }} /data"
    when: data.stat.isdir is defined and data.stat.isdir

  - name: Delete the html_root dir if isdir
    file:
        path: "{{html_root}}"
        state: absent
    when: sym.stat.isdir is defined and sym.stat.isdir

  - name: Symlink html_root to /data
    file:
        dest: "{{ html_root }}"
        src: "/data"
        state: link
    when: data.stat.isdir is defined and data.stat.isdir

  - name: Enable the httpd service
    service:
      name: httpd
      state: started
      enabled: true
