---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  vars:
    html_root: /var/www/html
  tasks:
  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Install apache
    apt:
      force_apt_get: yes
      name: apache2
      state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present

  - name: Bootstrap the box
    copy:
      src: bootstrap.sh
      dest: /tmp/bootstrap.sh
      mode: 0755

  - name: Run the bootstrap script
    shell: /tmp/bootstrap.sh

  - name: DOCKER - DWVA - PORT 808
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      published_ports: 808:80

  - name: DOCKER - PROJECT1 - PORT 8080
    docker_container:
      name: resume
      image: cyberxsecurity/project1-apachewebserver
      state: started
      published_ports: 8080:80

  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes
# Check to make sure nvme disks are partitioned and mounted.
  - name: "Stat the /data dir to see if it exists"
    stat:
        path: "/data"
    register: data

  - name: "Stat the {{ html_root }} to see if its dir or link"
    stat:
        path: "{{ html_root }}"
    register: sym

  - name: "Copy index.html to /data"
    copy:
      src: index.html
      dest: /data/index.html
      owner: www-data
      group: www-data
      mode: 0644
    when: data.stat.isdir is defined and data.stat.isdir

  - name: Delete the html_root dir if isdir
    file:
        path: "{{html_root}}"
        state: absent
    when: sym.stat.isdir is defined and sym.stat.isdir

  - name: Symlink html_root to /data
    file:
        dest: "{{ html_root }}"
        src: "/data"
        state: link
    when: data.stat.isdir is defined and data.stat.isdir

  - name: DISABLE the httpd service
    service:
      name: apache2
      state: stopped
      enabled: true

- name: Configure Elk VM with Docker
  hosts: elkservers
  become: true
  tasks:
    - name: Install docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

    - name: Install python3-pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: Install Docker module
      pip:
        name: docker
        state: present

    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        # Please list the ports that ELK runs on
        published_ports:
          -  5601:5601
          -  9200:9200
          -  5044:5044
      # Use systemd module
    - name: Enable service docker on boot
      systemd:
        name: docker
        enabled: yes
