---
- hosts: controller.do.iot4.net
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Copy the dvwa template
      copy:
        src: dvwa.yml
        dest: $HOME/dvwa.yml

    - name: Use kubectl to deploy the dvwa service
      shell: kubectl apply -f dvwa.yml >> dvwa.txt
      args:
        chdir: $HOME
        creates: dvwa.txt

    - name: Copy the mutillidae template
      copy:
        src: mutillidae.yml
        dest: $HOME/mutillidae.yml

    - name: Use kubectl to deploy the mutillidae service
      shell: kubectl apply -f mutillidae.yml >> mutillidae.txt
      args:
        chdir: $HOME
        creates: mutillidae.txt


    - name: Copy the webgoat template
      copy:
        src: webgoat.yml
        dest: $HOME/webgoat.yml

    - name: Use kubectl to deploy the webgoat service
      shell: kubectl apply -f webgoat.yml >> webgoat.txt
      args:
        chdir: $HOME
        creates: webgoat.txt

    - name: Copy the leza template
      copy:
        src: leza.yml
        dest: $HOME/leza.yml

    - name: Use kubectl to deploy the leza service
      shell: kubectl apply -f leza.yml >> leza.txt
      args:
        chdir: $HOME
        creates: leza.txt

- hosts: worker-0.do.iot4.net
  become: yes
  gather_facts: false
  tasks:
    - name: Add apache2 web server on worker-0 using apt
      apt:
        name: apache2
        update_cache: yes
        state: present
    - name: Transfer over our index.html file
      copy:
        src: index.html
        dest: /var/www/html

- hosts: worker-1.do.iot4.net
  become: yes
  gather_facts: false
  tasks:
    - name: Add nginx web server on worker-1 using apt
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Transfer over our index.html file
      copy:
        src: index.html
        dest: /var/www/html
